apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: grpc-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: azarec/grpc-client:latest
          imagePullPolicy: Always
          env:
            - name: SERVER_ADDR
              value: "grpc-server-service.svc"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: grpc-server
spec:
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: azarec/grpc-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "250m"
          env:
            - name: PORT
              value: "3000"

