apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-server-hpa
  labels:
    app: grpc-server
spec:
  maxReplicas: 20
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-deployment
  minReplicas: 3
  targetCPUUtilizationPercentage: 20
